services:
  prestashop:
    image: teravista/be_188555:latest
    user: root
    ports:
      - 18855:443
    depends_on:
      - memcached
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 70s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      PS_DEV_MODE: 0
      PS_INSTALL_AUTO: 1
      PS_FOLDER_INSTALL: install-dev
      PS_FOLDER_ADMIN: admin-dev
      DB_SERVER: db
      DB_USER: root
      DB_NAME: BE_188555
      DB_PASSWD: student
      PS_COUNTRY: pl
      PS_LANGUAGE: pl
      ADMIN_MAIL: demo@prestashop.com
      ADMIN_PASSWD: 12345678
    networks:
      - admin-mysql_default

  memcached:
    image: memcached
    container_name: BE_188555_memcached
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - admin-mysql_default

networks:
  admin-mysql_default:
    external: true
