FROM prestashop/prestashop:1.7.8

COPY ./apache.conf /etc/apache2/sites-available/ssl.conf

COPY ./certs/sslcert.crt /etc/ssl/certs/sslcert.crt
COPY ./certs/sslcert.crt /usr/local/share/ca-certificates/sslcert.crt
COPY ./certs/sslcert.key /etc/ssl/private/sslcert.key
COPY ./html/ /var/www/html/

RUN update-ca-certificates
RUN a2enmod ssl
RUN a2ensite ssl
